void main() {
   print ('Marksheet');
 var name = 'Name:     Asad Ullah Wahid';
  print (name);
 var fname = ('Father:   Muhammad Wahid');
  print (fname);
 var str1 = 'College: Govt Degree Boys College';
  print (str1);
  var str2= 'S.No    Subjects     Max Marks    Marks Obtained   Result  Grade ' ;
  print (str2);
  var str3= '1        English      100          80              Pass    B+';
  print (str3);
  var str4= '2        Maths        100          75              Pass    B';
  print (str4);
  var str5= '3        Urdu         100          78              Pass    B';
  print (str5);
  var str6= '4        Physics      100          81              Pass    B+';  
  print (str6);
  var str7= '5        Chemisrty    100          83              Pass    B+';
  print(str7);
  var str8= '         Grand Total  500          397             ' ;
  print(str8);
  var str9= '         Over All Percentage                       79.4% ';
  print (str9);

  }
